import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar gerada a partir da estrutura de pastas em docs/.
// A ordem e os rótulos das categorias ficam nos arquivos _category_.json.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
